# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='uploadTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
