# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0002_auto_20180618_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='uploadTime',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
