# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0005_auto_20180618_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='uploadTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 18, 13, 28, 46, 600592, tzinfo=utc)),
        ),
    ]
