# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0009_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='mysubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
            ],
        ),
    ]
