# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0011_auto_20180619_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='subjects',
            field=models.CharField(max_length=100),
        ),
    ]
