# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0012_auto_20180619_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='assignmentDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
