# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0014_auto_20180619_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='assignmentDate',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
