# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0015_auto_20180619_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='submission',
        ),
    ]
