# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0016_delete_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileUpload', models.FileField(upload_to=b'')),
                ('usn', models.CharField(max_length=100)),
                ('uploadTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('assignmentName', models.CharField(max_length=100)),
            ],
        ),
    ]
