# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0017_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='fileUpload',
            field=models.FileField(upload_to='path/'),
        ),
    ]
