# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0018_auto_20180619_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='fileUpload',
            field=models.FileField(upload_to=b''),
        ),
    ]
