# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySubmissions', '0019_auto_20180620_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='assignmentDate',
            field=models.CharField(max_length=2000),
        ),
    ]
